# PyEEG Snakemake Pipeline Configuration
# =====================================

# Core directories and paths
base_folder: "/mnt/isilon/marsh_single_unit/PythonEEG"
data_parent_folder: "/mnt/isilon/marsh_single_unit/PythonEEG Data Bins/Sox5/Dr. Lefebvre Project"
temp_directory: "/scr1/users/dongjp"

# Results directory structure
results_dir: "results"
wars_dir: "results/wars"
temporal_heatmaps_dir: "results/temporal_heatmaps"
diagnostic_figures_dir: "results/diagnostic_figures"
flattened_wars_dir: "results/flattened_wars"
final_analysis_dir: "results/final_analysis"

# Sample configuration
samples:
  # Sample metadata file path
  samples_file: "config/samples.json"
  
  # Quality filtering parameters
  quality_filter:
    exclude_unknown_genotypes: true
    exclude_bad_animaldays: true

# Analysis parameters
analysis:
  # WAR generation parameters
  war_generation:
    mode: "nest"
    assume_from_number: true
    skip_days: ["bad"]
    lro_kwargs:
      mode: "bin"
      multiprocess_mode: "dask"
      overwrite_rowbins: false

  # Data processing parameters for diagnostic figures and analysis
  processing:
    # Preprocessing - channel setup (applied before filtering)
    channel_reorder: ["LMot", "RMot", "LBar", "RBar", "LAud", "RAud", "LVis", "RVis"]
    use_abbrevs: true
    
    # Filtering parameters (passed directly to filter_all method)
    filtering:
      morphological_smoothing_seconds: null  # Temporal smoothing of artifact rejection mask
      bad_channels: ["LHip", "RHip"]  # Additional bad channels for filtering
      min_valid_channels: 3  # Minimum valid channels required per window
      # reject_channels: true  # Enable automatic channel rejection
      # reject_channels_by_session: false  # Per-session vs global channel rejection
    
    # Post-processing - aggregation (applied after filtering) 
    aggregation:
      groupby: ["animalday", "isday"]  # Time window grouping for aggregation

  # Figure generation parameters
  figures:
    coherecorr_spectral:
      figsize: [20, 5]
      score_type: "z"
    
    psd_histogram:
      figsize: [10, 4]
      avg_channels: true
      plot_type: "loglog"
    
    psd_spectrogram:
      figsize: [20, 4]
      mode: "none"
    
    # Temporal heatmap parameters - configurable features with individual parameters
    temporal_heatmaps:
      features:
        rms:
          figsize: [10, 3]
          cmap: "viridis"
          norm_type: "fixed"
          norm_params: 
            vmin: 50
            vmax: 300
        psdslope:
          figsize: [10, 3] 
          cmap: "viridis"
          norm_type: "fixed"
          norm_params:
            vmin: -3
            vmax: 0
        zpcorr:
          figsize: [10, 3]
          cmap: "RdBu_r"
          norm_type: "centered"
          norm_params:
            halfrange: 1.5

# SLURM cluster configuration
cluster:
  # WAR generation cluster (high-memory, high-core)
  war_generation:
    time: "3h"
    mem_mb: 70_000
    nodes: 1
    threads: 10
    interface: null

  # WAR quality filtering cluster (lightweight)
  war_quality_filter:
    time: "1h"
    mem_mb: 4_000
    nodes: 1
    threads: 1
    interface: null

  # Diagnostic figures cluster (single-animal, moderate resources)
  diagnostic_figures:
    time: "1h"
    mem_mb: 30_000
    nodes: 1
    threads: 4
    interface: null

  # WAR flattening cluster (high-memory, multiprocessing)
  war_flattening:
    time: "24h"
    mem_mb: 400_000
    nodes: 1
    threads: 14
    interface: null

  # Final analysis cluster (high-memory, multiprocessing)
  final_analysis:
    time: "24h"
    mem_mb: 409_600
    nodes: 1
    threads: 14
    interface: null

# Logging configuration
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(levelname)s - %(message)s"

# Feature exclusions for plotting
plotting:
  exclude_features: ["nspike", "lognspike"]
  catplot_params:
    showfliers: false
  plot_kinds: ["box", "swarm", "point"]